name: Steam Sale Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Restore notified cache
        uses: actions/cache@v4
        with:
          path: notified.json
          key: notified-cache
          restore-keys: notified-

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python bot.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Save notified cache
        uses: actions/cache/save@v4
        with:
          path: notified.json
          key: notified-cache
